package org.User.mapper;

import org.User.model.Orderdatail;

import java.util.List;

public interface OrderdatailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetail
     *
     * @mbg.generated Mon May 21 03:29:55 CST 2018
     */
    int insert(Orderdatail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetail
     *
     * @mbg.generated Mon May 21 03:29:55 CST 2018
     */
    List<Orderdatail> selectAll();
}