package org.User.model;

import java.util.Date;

public class Item {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column items.name
     *
     * @mbg.generated Mon May 21 03:29:55 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column items.price
     *
     * @mbg.generated Mon May 21 03:29:55 CST 2018
     */
    private Double price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column items.itemid
     *
     * @mbg.generated Mon May 21 03:29:55 CST 2018
     */
    private Integer itemid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column items.createtime
     *
     * @mbg.generated Mon May 21 03:29:55 CST 2018
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column items.pic
     *
     * @mbg.generated Mon May 21 03:29:55 CST 2018
     */
    private String pic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column items.detail
     *
     * @mbg.generated Mon May 21 03:29:55 CST 2018
     */
    private String detail;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column items.name
     *
     * @return the value of items.name
     *
     * @mbg.generated Mon May 21 03:29:55 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column items.name
     *
     * @param name the value for items.name
     *
     * @mbg.generated Mon May 21 03:29:55 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column items.price
     *
     * @return the value of items.price
     *
     * @mbg.generated Mon May 21 03:29:55 CST 2018
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column items.price
     *
     * @param price the value for items.price
     *
     * @mbg.generated Mon May 21 03:29:55 CST 2018
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column items.itemid
     *
     * @return the value of items.itemid
     *
     * @mbg.generated Mon May 21 03:29:55 CST 2018
     */
    public Integer getItemid() {
        return itemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column items.itemid
     *
     * @param itemid the value for items.itemid
     *
     * @mbg.generated Mon May 21 03:29:55 CST 2018
     */
    public void setItemid(Integer itemid) {
        this.itemid = itemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column items.createtime
     *
     * @return the value of items.createtime
     *
     * @mbg.generated Mon May 21 03:29:55 CST 2018
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column items.createtime
     *
     * @param createtime the value for items.createtime
     *
     * @mbg.generated Mon May 21 03:29:55 CST 2018
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column items.pic
     *
     * @return the value of items.pic
     *
     * @mbg.generated Mon May 21 03:29:55 CST 2018
     */
    public String getPic() {
        return pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column items.pic
     *
     * @param pic the value for items.pic
     *
     * @mbg.generated Mon May 21 03:29:55 CST 2018
     */
    public void setPic(String pic) {
        this.pic = pic == null ? null : pic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column items.detail
     *
     * @return the value of items.detail
     *
     * @mbg.generated Mon May 21 03:29:55 CST 2018
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column items.detail
     *
     * @param detail the value for items.detail
     *
     * @mbg.generated Mon May 21 03:29:55 CST 2018
     */
    public void setDetail(String detail) {
        this.detail = detail == null ? null : detail.trim();
    }
}