package org.User.model;

public class Orderdatail {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderdetail.detailId
     *
     * @mbg.generated Mon May 21 03:29:55 CST 2018
     */
    private Integer detailid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderdetail.order_id
     *
     * @mbg.generated Mon May 21 03:29:55 CST 2018
     */
    private Integer orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderdetail.item_id
     *
     * @mbg.generated Mon May 21 03:29:55 CST 2018
     */
    private Integer itemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderdetail.item_num
     *
     * @mbg.generated Mon May 21 03:29:55 CST 2018
     */
    private Integer itemNum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderdetail.detailId
     *
     * @return the value of orderdetail.detailId
     *
     * @mbg.generated Mon May 21 03:29:55 CST 2018
     */
    public Integer getDetailid() {
        return detailid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderdetail.detailId
     *
     * @param detailid the value for orderdetail.detailId
     *
     * @mbg.generated Mon May 21 03:29:55 CST 2018
     */
    public void setDetailid(Integer detailid) {
        this.detailid = detailid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderdetail.order_id
     *
     * @return the value of orderdetail.order_id
     *
     * @mbg.generated Mon May 21 03:29:55 CST 2018
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderdetail.order_id
     *
     * @param orderId the value for orderdetail.order_id
     *
     * @mbg.generated Mon May 21 03:29:55 CST 2018
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderdetail.item_id
     *
     * @return the value of orderdetail.item_id
     *
     * @mbg.generated Mon May 21 03:29:55 CST 2018
     */
    public Integer getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderdetail.item_id
     *
     * @param itemId the value for orderdetail.item_id
     *
     * @mbg.generated Mon May 21 03:29:55 CST 2018
     */
    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderdetail.item_num
     *
     * @return the value of orderdetail.item_num
     *
     * @mbg.generated Mon May 21 03:29:55 CST 2018
     */
    public Integer getItemNum() {
        return itemNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderdetail.item_num
     *
     * @param itemNum the value for orderdetail.item_num
     *
     * @mbg.generated Mon May 21 03:29:55 CST 2018
     */
    public void setItemNum(Integer itemNum) {
        this.itemNum = itemNum;
    }
}